# 作者:柠枺
# 源代码由ai提供，无法保证稳定性！
#-------------------------------
#              ==基础配置==
#-------------------------------

# 是否启用昵称占位符支持
# 可能会对假人有用，但是没人会拿假人当npc，对吧？
placeholder: false

# 屏蔽词列表
Block-words:
  - sb
  - 傻逼

# 是否覆盖聊天，从而不使用其他风格聊天插件?
covering-chat: false

# 覆盖聊天格式
# 可用变量:
# - {pnn} 直接显示玩家昵称
# - {pnn_ID} 在玩家ID前显示昵称
# - {ID_pnn} 在玩家ID后显示昵称
# - {message} 玩家消息
covering-chat-formats: "&{pnn_ID} &f>>> {message}"

# 是否覆盖tab栏玩家ID
cover-tab: false

# tab栏覆盖ID格式
# 可用变量同上
cover-tab-formats: "&{pnn}"

# 是否覆盖玩家头
cover-head: false

# 玩家头显示格式
# 可用变量同上
cover-head-formats: "&{pnn}"

#-------------------------------
#              ==数据保存模式==
#-------------------------------

# 可用:yaml，sqlite，MySQL
# 默认yaml
data-saving-mode: yaml

# MySQL数据库配置
mysql:
  host: "localhost"
  port: 3306
  database: "database"
  username: "username"
  password: "password" 